### ISSUE TITLE
Status Inquiry

### ISSUE THREAD

**Issue by ugochukwu-850** [dcl10/py-tauri#5]
@dcl10  Do you still need help on a making this work , or have you abandoned it. Well I am asking because , I am considering trying , I just want to be sure it would not be wasted effort

**Comment by dcl10** [comment]
Hi @ugochukwu-850, I started this as some research for something at work. For the sake as expedience, I won't be taking it forward. However, if you'd like to fork this repo on your own time and make a PR if you solve it, I would be interested in seeing how you solve the problem.

I'm particularly interested in seeing how one statically embeds a python interpreter along with the python standard library and site packages (i.e. packages installed from `pip`). An alternative might be using the Tauri sidecar with an application packaged with `pyinstaller`.

Don't feel pressured to work on this if you don't want to or are not interested. It's not urgent to me at all. Thank you for offering, though 😄

**Comment by ugochukwu-850** [comment]
@dcl10 Thanks for the response , well its possible to actually embed the python interpreter along with the std lib and the packages you would need , its just a rabbit hole I would not want to go down , especially if there is not a good cause to it , but on the other hand running the python code as a binary - after packaging with pyinstaller - should not be hard, at all infact I did something like that in my last project [@Jomify](https://github.com/ugochukwu-850/Jomify), well since it is not something of optimum priority for you but it is still intriguing for me , I would just play around with it , on my spare time , and If I happen to get it working , I'd share it with you ..
